[package]
name = "rylv-serde-json-test"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "test.rs"

[dependencies]
rylv-serde-json = { path = "../..", default-features = false }

[features]
default = ["std"]
std = ["rylv-serde-json/std"]
alloc = ["rylv-serde-json/alloc"]
#preserve_order = ["rylv-serde-json/preserve_order"]
float_roundtrip = ["rylv-serde-json/float_roundtrip"]
arbitrary_precision = ["rylv-serde-json/arbitrary_precision"]
raw_value = ["rylv-serde-json/raw_value"]
unbounded_depth = ["rylv-serde-json/unbounded_depth"]
